AWSTemplateFormatVersion: '2010-09-09'
Transform: AWS::Serverless-2016-10-31
Resources:
  TagFunction:
    Type: AWS::Serverless::Function
    Properties:
      Handler: main.handler
      Runtime: python3.7
      Environment:
        Variables: 
          ERROR_SNS_TOPIC_ARN: 'arn:aws:sns:ap-northeast-1:...' # Modify this
      # Tags:
      #   Cost: ''
      Events:
        sns:
          Type: SNS
          Properties:
            Topic: 'arn:...' # Modify this
      Policies:
      - Version: '2012-10-17'
        Statement:
        - Effect: Allow
          Action:
          - s3:GetObject
          Resource: 'arn:...' # Modify this
        - Effect: Allow
          Action:
          - ec2:CreateTags
          Resource: '*'
        - Effect: Allow
          Action:
          - sns:Publish
          Resource: 'arn:...' # Modify this

